# Site settings
title: HennyJie
email: cuihejie331771@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to HennyJie's Blog.
baseurl: "/HennyJie's Blog" # the subpath of your site, e.g. /blog/
url: "http://cuihejie.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  HennyJie

# Build settings
markdown: kramdown
